name: Build and Publish Azure Functions

on:
  push:
    branches: 
      - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: build and package Azure Functions
      run: |
        dotnet restore
        dotnet build -c Release
        #dotnet test --no-build --verbosity normal
        dotnet publish -c Release -o dist
        
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.8
      with:
        # Name of the Azure Function App
        app-name: hellofn
        
        # Path to package or folder. *.zip or a folder to deploy
        package: dist

        # Publish profile (*.publishsettings) file contents with web deploy secrets
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        
        
        
